services:
  backend:
    container_name: gaishi-backend
    depends_on:
      - db
    build:
      context: ./
      dockerfile: backend/build/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  db:
    container_name: gaishi-db
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: gaishi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    container_name: gaishi-adminer
    image: adminer
    restart: always
    ports:
      - 6666:8080

volumes:
  db_data:
