name: Common Google Cloud Auth

on:
  workflow_call:

jobs:
  auth:
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ jobs.auth.outputs.access_token }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Login to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GOOGLE_SERVICE_ACCOUNT }}
