name: Common Google Cloud Auth

on:
  workflow_call:

jobs:
  auth:
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.auth.outputs.access_token }}
    steps:
      - name: Login to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ var.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ var.GOOGLE_SERVICE_ACCOUNT }}
