export const sampleGenres = {
  ja: [
    {
      id: "aaaaa",
      label: "限定",
    },
    {
      id: "bbbbb",
      label: "おすすめ",
    },
    {
      id: "ccccc",
      label: "単品",
    },
    {
      id: "ddddd",
      label: "セット",
    },
    {
      id: "eeeee",
      label: "ドリンク",
    },
    {
      id: "fffff",
      label: "デザート",
    },
    {
      id: "ggggg",
      label: "物販",
    },
  ],
  en: [
    {
      id: "aaaaa",
      label: "Limited",
    },
    {
      id: "bbbbb",
      label: "Recommended",
    },
    {
      id: "ccccc",
      label: "Single Item",
    },
    {
      id: "ddddd",
      label: "Set",
    },
    {
      id: "eeeee",
      label: "Drink",
    },
    {
      id: "fffff",
      label: "Dessert",
    },
    {
      id: "ggggg",
      label: "Merchandise",
    },
  ],
  zh: [
    {
      id: "aaaaa",
      label: "限定",
    },
    {
      id: "bbbbb",
      label: "推荐",
    },
    {
      id: "ccccc",
      label: "单品",
    },
    {
      id: "ddddd",
      label: "套餐",
    },
    {
      id: "eeeee",
      label: "饮料",
    },
    {
      id: "fffff",
      label: "甜点",
    },
    {
      id: "ggggg",
      label: "商品",
    },
  ],
  ko: [
    {
      id: "aaaaa",
      label: "한정",
    },
    {
      id: "bbbbb",
      label: "추천",
    },
    {
      id: "ccccc",
      label: "단품",
    },
    {
      id: "ddddd",
      label: "세트",
    },
    {
      id: "eeeee",
      label: "음료",
    },
    {
      id: "fffff",
      label: "디저트",
    },
    {
      id: "ggggg",
      label: "물품",
    },
  ],
  es: [
    {
      id: "aaaaa",
      label: "Limited",
    },
    {
      id: "bbbbb",
      label: "Recomendado",
    },
    {
      id: "ccccc",
      label: "Article unique",
    },
    {
      id: "ddddd",
      label: "Ensemble",
    },
    {
      id: "eeeee",
      label: "Boisson",
    },
    {
      id: "fffff",
      label: "Dessert",
    },
    {
      id: "ggggg",
      label: "Marchandises",
    },
  ],
  fr: [
    {
      id: "aaaaa",
      label: "Limité",
    },
    {
      id: "bbbbb",
      label: "Recommandé",
    },
    {
      id: "ccccc",
      label: "Article unique",
    },
    {
      id: "ddddd",
      label: "Ensemble",
    },
    {
      id: "eeeee",
      label: "Boisson",
    },
    {
      id: "fffff",
      label: "Dessert",
    },
    {
      id: "ggggg",
      label: "Marchandises",
    },
  ],
  th: [
    {
      id: "aaaaa",
      label: "จำกัด",
    },
    {
      id: "bbbbb",
      label: "แนะนำ",
    },
    {
      id: "ccccc",
      label: "สินค้าชิ้นเดียว",
    },
    {
      id: "ddddd",
      label: "ชุด",
    },
    {
      id: "eeeee",
      label: "เครื่องดื่ม",
    },
    {
      id: "fffff",
      label: "ขนมหวาน",
    },
    {
      id: "ggggg",
      label: "สินค้า",
    },
  ],
  de: [
    {
      id: "aaaaa",
      label: "Begrenzt",
    },
    {
      id: "bbbbb",
      label: "Empfohlen",
    },
    {
      id: "ccccc",
      label: "Einzelartikel",
    },
    {
      id: "ddddd",
      label: "Set",
    },
    {
      id: "eeeee",
      label: "Getränk",
    },
    {
      id: "fffff",
      label: "Dessert",
    },
    {
      id: "ggggg",
      label: "Waren",
    },
  ],
  ru: [
    {
      id: "aaaaa",
      label: "Ограничено",
    },
    {
      id: "bbbbb",
      label: "Рекомендуется",
    },
    {
      id: "ccccc",
      label: "Одиночный элемент",
    },
    {
      id: "ddddd",
      label: "Набор",
    },
    {
      id: "eeeee",
      label: "Напиток",
    },
    {
      id: "fffff",
      label: "Десерт",
    },
    {
      id: "ggggg",
      label: "Товары",
    },
  ],
  it: [
    {
      id: "aaaaa",
      label: "Limitato",
    },
    {
      id: "bbbbb",
      label: "Consigliato",
    },
    {
      id: "ccccc",
      label: "Articolo singolo",
    },
    {
      id: "ddddd",
      label: "Set",
    },
    {
      id: "eeeee",
      label: "Bevanda",
    },
    {
      id: "fffff",
      label: "Dessert",
    },
    {
      id: "ggggg",
      label: "Merce",
    },
  ],
};

export const sampleMenuItems = {
  ja: [
    {
      id: "0000",
      name: "濃厚担々麺",
      genreId: "aaaaa",
      price: 900,
      image: "/buckwheat.jpg",
    },
    {
      id: "1111",
      name: "特製カレー",
      genreId: "aaaaa",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "4444",
      name: "贅沢寿盛り合わせ",
      genreId: "aaaaa",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "6666",
      name: "特製バーガー",
      genreId: "bbbbb",
      price: 1000,
      image: "/buckwheat.jpg",
    },
    {
      id: "7777",
      name: "海鮮丼",
      genreId: "bbbbb",
      price: 1300,
      image: "/buckwheat.jpg",
    },
    {
      id: "9999",
      name: "クラシックピザ",
      genreId: "bbbbb",
      price: 1100,
      image: "/buckwheat.jpg",
    },
    {
      id: "zzzz",
      name: "フライドポテト",
      genreId: "ccccc",
      price: 500,
      image: "/buckwheat.jpg",
    },
    {
      id: "xxxx",
      name: "唐揚げ",
      genreId: "ccccc",
      price: 600,
      image: "/buckwheat.jpg",
    },
    {
      id: "wwww",
      name: "サラダ",
      genreId: "ccccc",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "tttt",
      name: "お子様セット",
      genreId: "ddddd",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "ssss",
      name: "和風定食セット",
      genreId: "ddddd",
      price: 1200,
      image: "/buckwheat.jpg",
    },
    {
      id: "rrrr",
      name: "洋風ディナーセット",
      genreId: "ddddd",
      price: 2000,
      image: "/buckwheat.jpg",
    },
    {
      id: "pppp",
      name: "コーラ",
      genreId: "eeeee",
      price: 200,
      image: "/buckwheat.jpg",
    },
    {
      id: "oooo",
      name: "オレンジジュース",
      genreId: "eeeee",
      price: 250,
      image: "/buckwheat.jpg",
    },
    {
      id: "nnnn",
      name: "ウーロン茶",
      genreId: "eeeee",
      price: 220,
      image: "/buckwheat.jpg",
    },
    {
      id: "iiii",
      name: "抹茶アイス",
      genreId: "fffff",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "hhhh",
      name: "フルーツ盛り合わせ",
      genreId: "fffff",
      price: 700,
      image: "/buckwheat.jpg",
    },
    {
      id: "gggg",
      name: "プリン",
      genreId: "fffff",
      price: 450,
      image: "/buckwheat.jpg",
    },
    {
      id: "ffff",
      name: "お土産クッキー",
      genreId: "ggggg",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "cccc",
      name: "特製コーヒー豆",
      genreId: "ggggg",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "bbbb",
      name: "マグカップ",
      genreId: "ggggg",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  en: [
    {
      id: "0000",
      name: "Rich Spicy Tantanmen (Japanese Ramen with Sesame Sauce)",
      genreId: "aaaaa",
      price: 900,
      image: "/buckwheat.jpg",
    },
    {
      id: "1111",
      name: "Special Japanese Curry",
      genreId: "aaaaa",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "4444",
      name: "Premium Sushi Platter",
      genreId: "aaaaa",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "6666",
      name: "Special Burger",
      genreId: "bbbbb",
      price: 1000,
      image: "/buckwheat.jpg",
    },
    {
      id: "7777",
      name: "Seafood Rice Bowl (Kaisendon)",
      genreId: "bbbbb",
      price: 1300,
      image: "/buckwheat.jpg",
    },
    {
      id: "9999",
      name: "Classic Pizza",
      genreId: "bbbbb",
      price: 1100,
      image: "/buckwheat.jpg",
    },
    {
      id: "zzzz",
      name: "French Fries",
      genreId: "ccccc",
      price: 500,
      image: "/buckwheat.jpg",
    },
    {
      id: "xxxx",
      name: "Japanese Fried Chicken (Karaage)",
      genreId: "ccccc",
      price: 600,
      image: "/buckwheat.jpg",
    },
    {
      id: "wwww",
      name: "Fresh Salad",
      genreId: "ccccc",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "tttt",
      name: "Kids' Meal Set",
      genreId: "ddddd",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "ssss",
      name: "Japanese Style Meal Set",
      genreId: "ddddd",
      price: 1200,
      image: "/buckwheat.jpg",
    },
    {
      id: "rrrr",
      name: "Western Dinner Set",
      genreId: "ddddd",
      price: 2000,
      image: "/buckwheat.jpg",
    },
    {
      id: "pppp",
      name: "Cola",
      genreId: "eeeee",
      price: 200,
      image: "/buckwheat.jpg",
    },
    {
      id: "oooo",
      name: "Orange Juice",
      genreId: "eeeee",
      price: 250,
      image: "/buckwheat.jpg",
    },
    {
      id: "nnnn",
      name: "Oolong Tea",
      genreId: "eeeee",
      price: 220,
      image: "/buckwheat.jpg",
    },
    {
      id: "iiii",
      name: "Matcha Ice Cream",
      genreId: "fffff",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "hhhh",
      name: "Fruit Platter",
      genreId: "fffff",
      price: 700,
      image: "/buckwheat.jpg",
    },
    {
      id: "gggg",
      name: "Pudding",
      genreId: "fffff",
      price: 450,
      image: "/buckwheat.jpg",
    },
    {
      id: "ffff",
      name: "Souvenir Cookies",
      genreId: "ggggg",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "cccc",
      name: "Special Coffee Beans",
      genreId: "ggggg",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "bbbb",
      name: "Mug Cup",
      genreId: "ggggg",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  zh: [
    {
      id: "0000",
      name: "浓厚担担面",
      genreId: "aaaaa",
      price: 900,
      image: "/buckwheat.jpg",
    },
    {
      id: "1111",
      name: "特制咖喱",
      genreId: "aaaaa",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "4444",
      name: "豪华寿司拼盘",
      genreId: "aaaaa",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "6666",
      name: "特制汉堡",
      genreId: "bbbbb",
      price: 1000,
      image: "/buckwheat.jpg",
    },
    {
      id: "7777",
      name: "海鲜盖饭",
      genreId: "bbbbb",
      price: 1300,
      image: "/buckwheat.jpg",
    },
    {
      id: "9999",
      name: "经典披萨",
      genreId: "bbbbb",
      price: 1100,
      image: "/buckwheat.jpg",
    },
    {
      id: "zzzz",
      name: "炸薯条",
      genreId: "ccccc",
      price: 500,
      image: "/buckwheat.jpg",
    },
    {
      id: "xxxx",
      name: "日式炸鸡",
      genreId: "ccccc",
      price: 600,
      image: "/buckwheat.jpg",
    },
    {
      id: "wwww",
      name: "新鲜沙拉",
      genreId: "ccccc",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "tttt",
      name: "儿童套餐",
      genreId: "ddddd",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "ssss",
      name: "日式定食套餐",
      genreId: "ddddd",
      price: 1200,
      image: "/buckwheat.jpg",
    },
    {
      id: "rrrr",
      name: "西式晚餐套餐",
      genreId: "ddddd",
      price: 2000,
      image: "/buckwheat.jpg",
    },
    {
      id: "pppp",
      name: "可乐",
      genreId: "eeeee",
      price: 200,
      image: "/buckwheat.jpg",
    },
    {
      id: "oooo",
      name: "橙汁",
      genreId: "eeeee",
      price: 250,
      image: "/buckwheat.jpg",
    },
    {
      id: "nnnn",
      name: "乌龙茶",
      genreId: "eeeee",
      price: 220,
      image: "/buckwheat.jpg",
    },
    {
      id: "iiii",
      name: "抹茶冰淇淋",
      genreId: "fffff",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "hhhh",
      name: "水果拼盘",
      genreId: "fffff",
      price: 700,
      image: "/buckwheat.jpg",
    },
    {
      id: "gggg",
      name: "布丁",
      genreId: "fffff",
      price: 450,
      image: "/buckwheat.jpg",
    },
    {
      id: "ffff",
      name: "纪念饼干",
      genreId: "ggggg",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "cccc",
      name: "特制咖啡豆",
      genreId: "ggggg",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "bbbb",
      name: "马克杯",
      genreId: "ggggg",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  ko: [
    {
      id: "0000",
      name: "진한 탄탄멘",
      genreId: "aaaaa",
      price: 900,
      image: "/buckwheat.jpg",
    },
    {
      id: "1111",
      name: "특제 카레",
      genreId: "aaaaa",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "4444",
      name: "고급 스시 모둠",
      genreId: "aaaaa",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "6666",
      name: "특제 버거",
      genreId: "bbbbb",
      price: 1000,
      image: "/buckwheat.jpg",
    },
    {
      id: "7777",
      name: "해산물 덮밥",
      genreId: "bbbbb",
      price: 1300,
      image: "/buckwheat.jpg",
    },
    {
      id: "9999",
      name: "클래식 피자",
      genreId: "bbbbb",
      price: 1100,
      image: "/buckwheat.jpg",
    },
    {
      id: "zzzz",
      name: "프렌치 프라이",
      genreId: "ccccc",
      price: 500,
      image: "/buckwheat.jpg",
    },
    {
      id: "xxxx",
      name: "일본식 튀김 치킨",
      genreId: "ccccc",
      price: 600,
      image: "/buckwheat.jpg",
    },
    {
      id: "wwww",
      name: "신선한 샐러드",
      genreId: "ccccc",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "tttt",
      name: "어린이 세트",
      genreId: "ddddd",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "ssss",
      name: "일식 정식 세트",
      genreId: "ddddd",
      price: 1200,
      image: "/buckwheat.jpg",
    },
    {
      id: "rrrr",
      name: "서양식 저녁 세트",
      genreId: "ddddd",
      price: 2000,
      image: "/buckwheat.jpg",
    },
    {
      id: "pppp",
      name: "콜라",
      genreId: "eeeee",
      price: 200,
      image: "/buckwheat.jpg",
    },
    {
      id: "oooo",
      name: "오렌지 주스",
      genreId: "eeeee",
      price: 250,
      image: "/buckwheat.jpg",
    },
    {
      id: "nnnn",
      name: "우롱차",
      genreId: "eeeee",
      price: 220,
      image: "/buckwheat.jpg",
    },
    {
      id: "iiii",
      name: "말차 아이스크림",
      genreId: "fffff",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "hhhh",
      name: "과일 모둠",
      genreId: "fffff",
      price: 700,
      image: "/buckwheat.jpg",
    },
    {
      id: "gggg",
      name: "푸딩",
      genreId: "fffff",
      price: 450,
      image: "/buckwheat.jpg",
    },
    {
      id: "ffff",
      name: "기념 쿠키",
      genreId: "ggggg",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "cccc",
      name: "특제 커피 원두",
      genreId: "ggggg",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "bbbb",
      name: "머그컵",
      genreId: "ggggg",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  es: [
    {
      id: "0000",
      name: "Tantanmen Picante Rico",
      genreId: "aaaaa",
      price: 900,
      image: "/buckwheat.jpg",
    },
    {
      id: "1111",
      name: "Curry Especial",
      genreId: "aaaaa",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "4444",
      name: "Surtido de Sushi de Lujo",
      genreId: "aaaaa",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "6666",
      name: "Hamburguesa Especial",
      genreId: "bbbbb",
      price: 1000,
      image: "/buckwheat.jpg",
    },
    {
      id: "7777",
      name: "Tazón de Arroz con Mariscos",
      genreId: "bbbbb",
      price: 1300,
      image: "/buckwheat.jpg",
    },
    {
      id: "9999",
      name: "Pizza Clásica",
      genreId: "bbbbb",
      price: 1100,
      image: "/buckwheat.jpg",
    },
    {
      id: "zzzz",
      name: "Papas Fritas",
      genreId: "ccccc",
      price: 500,
      image: "/buckwheat.jpg",
    },
    {
      id: "xxxx",
      name: "Pollo Frito Japonés",
      genreId: "ccccc",
      price: 600,
      image: "/buckwheat.jpg",
    },
    {
      id: "wwww",
      name: "Ensalada Fresca",
      genreId: "ccccc",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "tttt",
      name: "Menú Infantil",
      genreId: "ddddd",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "ssss",
      name: "Menú Estilo Japonés",
      genreId: "ddddd",
      price: 1200,
      image: "/buckwheat.jpg",
    },
    {
      id: "rrrr",
      name: "Menú de Cena Occidental",
      genreId: "ddddd",
      price: 2000,
      image: "/buckwheat.jpg",
    },
    {
      id: "pppp",
      name: "Cola",
      genreId: "eeeee",
      price: 200,
      image: "/buckwheat.jpg",
    },
    {
      id: "oooo",
      name: "Jugo de Naranja",
      genreId: "eeeee",
      price: 250,
      image: "/buckwheat.jpg",
    },
    {
      id: "nnnn",
      name: "Té Oolong",
      genreId: "eeeee",
      price: 220,
      image: "/buckwheat.jpg",
    },
    {
      id: "iiii",
      name: "Helado de Matcha",
      genreId: "fffff",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "hhhh",
      name: "Surtido de Frutas",
      genreId: "fffff",
      price: 700,
      image: "/buckwheat.jpg",
    },
    {
      id: "gggg",
      name: "Pudín",
      genreId: "fffff",
      price: 450,
      image: "/buckwheat.jpg",
    },
    {
      id: "ffff",
      name: "Galletas de Recuerdo",
      genreId: "ggggg",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "cccc",
      name: "Granos de Café Especiales",
      genreId: "ggggg",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "bbbb",
      name: "Taza",
      genreId: "ggggg",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  fr: [
    {
      id: "0000",
      name: "Tantanmen Épicé Riche",
      genreId: "aaaaa",
      price: 900,
      image: "/buckwheat.jpg",
    },
    {
      id: "1111",
      name: "Curry Spécial",
      genreId: "aaaaa",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "4444",
      name: "Plateau de Sushi de Luxe",
      genreId: "aaaaa",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "6666",
      name: "Burger Spécial",
      genreId: "bbbbb",
      price: 1000,
      image: "/buckwheat.jpg",
    },
    {
      id: "7777",
      name: "Bol de Riz aux Fruits de Mer",
      genreId: "bbbbb",
      price: 1300,
      image: "/buckwheat.jpg",
    },
    {
      id: "9999",
      name: "Pizza Classique",
      genreId: "bbbbb",
      price: 1100,
      image: "/buckwheat.jpg",
    },
    {
      id: "zzzz",
      name: "Frites",
      genreId: "ccccc",
      price: 500,
      image: "/buckwheat.jpg",
    },
    {
      id: "xxxx",
      name: "Poulet Frit Japonais",
      genreId: "ccccc",
      price: 600,
      image: "/buckwheat.jpg",
    },
    {
      id: "wwww",
      name: "Salade Fraîche",
      genreId: "ccccc",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "tttt",
      name: "Menu Enfant",
      genreId: "ddddd",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "ssss",
      name: "Menu Style Japonais",
      genreId: "ddddd",
      price: 1200,
      image: "/buckwheat.jpg",
    },
    {
      id: "rrrr",
      name: "Menu Dîner Occidental",
      genreId: "ddddd",
      price: 2000,
      image: "/buckwheat.jpg",
    },
    {
      id: "pppp",
      name: "Cola",
      genreId: "eeeee",
      price: 200,
      image: "/buckwheat.jpg",
    },
    {
      id: "oooo",
      name: "Jus d'Orange",
      genreId: "eeeee",
      price: 250,
      image: "/buckwheat.jpg",
    },
    {
      id: "nnnn",
      name: "Thé Oolong",
      genreId: "eeeee",
      price: 220,
      image: "/buckwheat.jpg",
    },
    {
      id: "iiii",
      name: "Glace au Matcha",
      genreId: "fffff",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "hhhh",
      name: "Plateau de Fruits",
      genreId: "fffff",
      price: 700,
      image: "/buckwheat.jpg",
    },
    {
      id: "gggg",
      name: "Flan",
      genreId: "fffff",
      price: 450,
      image: "/buckwheat.jpg",
    },
    {
      id: "ffff",
      name: "Biscuits Souvenir",
      genreId: "ggggg",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "cccc",
      name: "Grains de Café Spéciaux",
      genreId: "ggggg",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "bbbb",
      name: "Tasse",
      genreId: "ggggg",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  th: [
    {
      id: "0000",
      name: "บะหมี่ตันตันรสเข้มข้น",
      genreId: "aaaaa",
      price: 900,
      image: "/buckwheat.jpg",
    },
    {
      id: "1111",
      name: "แกงกะหรี่พิเศษ",
      genreId: "aaaaa",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "4444",
      name: "ซูชิชุดหรู",
      genreId: "aaaaa",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "6666",
      name: "เบอร์เกอร์พิเศษ",
      genreId: "bbbbb",
      price: 1000,
      image: "/buckwheat.jpg",
    },
    {
      id: "7777",
      name: "ข้าวหน้าทะเล",
      genreId: "bbbbb",
      price: 1300,
      image: "/buckwheat.jpg",
    },
    {
      id: "9999",
      name: "พิซซ่าคลาสสิก",
      genreId: "bbbbb",
      price: 1100,
      image: "/buckwheat.jpg",
    },
    {
      id: "zzzz",
      name: "เฟรนช์ฟรายส์",
      genreId: "ccccc",
      price: 500,
      image: "/buckwheat.jpg",
    },
    {
      id: "xxxx",
      name: "ไก่ทอดญี่ปุ่น",
      genreId: "ccccc",
      price: 600,
      image: "/buckwheat.jpg",
    },
    {
      id: "wwww",
      name: "สลัดสด",
      genreId: "ccccc",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "tttt",
      name: "ชุดอาหารเด็ก",
      genreId: "ddddd",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "ssss",
      name: "ชุดอาหารสไตล์ญี่ปุ่น",
      genreId: "ddddd",
      price: 1200,
      image: "/buckwheat.jpg",
    },
    {
      id: "rrrr",
      name: "ชุดอาหารค่ำสไตล์ตะวันตก",
      genreId: "ddddd",
      price: 2000,
      image: "/buckwheat.jpg",
    },
    {
      id: "pppp",
      name: "โคล่า",
      genreId: "eeeee",
      price: 200,
      image: "/buckwheat.jpg",
    },
    {
      id: "oooo",
      name: "น้ำส้ม",
      genreId: "eeeee",
      price: 250,
      image: "/buckwheat.jpg",
    },
    {
      id: "nnnn",
      name: "ชาอู่หลง",
      genreId: "eeeee",
      price: 220,
      image: "/buckwheat.jpg",
    },
    {
      id: "iiii",
      name: "ไอศกรีมมัทฉะ",
      genreId: "fffff",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "hhhh",
      name: "ผลไม้รวม",
      genreId: "fffff",
      price: 700,
      image: "/buckwheat.jpg",
    },
    {
      id: "gggg",
      name: "พุดดิ้ง",
      genreId: "fffff",
      price: 450,
      image: "/buckwheat.jpg",
    },
    {
      id: "ffff",
      name: "คุกกี้ของที่ระลึก",
      genreId: "ggggg",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "cccc",
      name: "เมล็ดกาแฟพิเศษ",
      genreId: "ggggg",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "bbbb",
      name: "แก้วมัค",
      genreId: "ggggg",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  de: [
    {
      id: "0000",
      name: "Würzige Tantanmen",
      genreId: "aaaaa",
      price: 900,
      image: "/buckwheat.jpg",
    },
    {
      id: "1111",
      name: "Spezial-Curry",
      genreId: "aaaaa",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "4444",
      name: "Luxus-Sushi-Platte",
      genreId: "aaaaa",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "6666",
      name: "Spezial-Burger",
      genreId: "bbbbb",
      price: 1000,
      image: "/buckwheat.jpg",
    },
    {
      id: "7777",
      name: "Meeresfrüchte-Reisschüssel",
      genreId: "bbbbb",
      price: 1300,
      image: "/buckwheat.jpg",
    },
    {
      id: "9999",
      name: "Klassische Pizza",
      genreId: "bbbbb",
      price: 1100,
      image: "/buckwheat.jpg",
    },
    {
      id: "zzzz",
      name: "Pommes Frites",
      genreId: "ccccc",
      price: 500,
      image: "/buckwheat.jpg",
    },
    {
      id: "xxxx",
      name: "Japanisches Brathähnchen",
      genreId: "ccccc",
      price: 600,
      image: "/buckwheat.jpg",
    },
    {
      id: "wwww",
      name: "Frischer Salat",
      genreId: "ccccc",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "tttt",
      name: "Kinder-Menü",
      genreId: "ddddd",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "ssss",
      name: "Japanisches Menü",
      genreId: "ddddd",
      price: 1200,
      image: "/buckwheat.jpg",
    },
    {
      id: "rrrr",
      name: "Westliches Abendessen-Menü",
      genreId: "ddddd",
      price: 2000,
      image: "/buckwheat.jpg",
    },
    {
      id: "pppp",
      name: "Cola",
      genreId: "eeeee",
      price: 200,
      image: "/buckwheat.jpg",
    },
    {
      id: "oooo",
      name: "Orangensaft",
      genreId: "eeeee",
      price: 250,
      image: "/buckwheat.jpg",
    },
    {
      id: "nnnn",
      name: "Oolong-Tee",
      genreId: "eeeee",
      price: 220,
      image: "/buckwheat.jpg",
    },
    {
      id: "iiii",
      name: "Matcha-Eiscreme",
      genreId: "fffff",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "hhhh",
      name: "Obstplatte",
      genreId: "fffff",
      price: 700,
      image: "/buckwheat.jpg",
    },
    {
      id: "gggg",
      name: "Pudding",
      genreId: "fffff",
      price: 450,
      image: "/buckwheat.jpg",
    },
    {
      id: "ffff",
      name: "Souvenir-Kekse",
      genreId: "ggggg",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "cccc",
      name: "Spezial-Kaffeebohnen",
      genreId: "ggggg",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "bbbb",
      name: "Tasse",
      genreId: "ggggg",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  ru: [
    {
      id: "0000",
      name: "Острый Тантанмен",
      genreId: "aaaaa",
      price: 900,
      image: "/buckwheat.jpg",
    },
    {
      id: "1111",
      name: "Специальное Карри",
      genreId: "aaaaa",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "4444",
      name: "Роскошный Суши Ассорти",
      genreId: "aaaaa",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "6666",
      name: "Специальный Бургер",
      genreId: "bbbbb",
      price: 1000,
      image: "/buckwheat.jpg",
    },
    {
      id: "7777",
      name: "Рисовая Чаша с Морепродуктами",
      genreId: "bbbbb",
      price: 1300,
      image: "/buckwheat.jpg",
    },
    {
      id: "9999",
      name: "Классическая Пицца",
      genreId: "bbbbb",
      price: 1100,
      image: "/buckwheat.jpg",
    },
    {
      id: "zzzz",
      name: "Картофель Фри",
      genreId: "ccccc",
      price: 500,
      image: "/buckwheat.jpg",
    },
    {
      id: "xxxx",
      name: "Японская Жареная Курица",
      genreId: "ccccc",
      price: 600,
      image: "/buckwheat.jpg",
    },
    {
      id: "wwww",
      name: "Свежий Салат",
      genreId: "ccccc",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "tttt",
      name: "Детское Меню",
      genreId: "ddddd",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "ssss",
      name: "Японский Набор",
      genreId: "ddddd",
      price: 1200,
      image: "/buckwheat.jpg",
    },
    {
      id: "rrrr",
      name: "Западный Ужин",
      genreId: "ddddd",
      price: 2000,
      image: "/buckwheat.jpg",
    },
    {
      id: "pppp",
      name: "Кола",
      genreId: "eeeee",
      price: 200,
      image: "/buckwheat.jpg",
    },
    {
      id: "oooo",
      name: "Апельсиновый Сок",
      genreId: "eeeee",
      price: 250,
      image: "/buckwheat.jpg",
    },
    {
      id: "nnnn",
      name: "Чай Улун",
      genreId: "eeeee",
      price: 220,
      image: "/buckwheat.jpg",
    },
    {
      id: "iiii",
      name: "Мороженое Матча",
      genreId: "fffff",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "hhhh",
      name: "Фруктовая Тарелка",
      genreId: "fffff",
      price: 700,
      image: "/buckwheat.jpg",
    },
    {
      id: "gggg",
      name: "Пудинг",
      genreId: "fffff",
      price: 450,
      image: "/buckwheat.jpg",
    },
    {
      id: "ffff",
      name: "Сувенирное Печенье",
      genreId: "ggggg",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "cccc",
      name: "Специальные Кофейные Зерна",
      genreId: "ggggg",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "bbbb",
      name: "Кружка",
      genreId: "ggggg",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  it: [
    {
      id: "0000",
      name: "Tantanmen Piccante Ricco",
      genreId: "aaaaa",
      price: 900,
      image: "/buckwheat.jpg",
    },
    {
      id: "1111",
      name: "Curry Speciale",
      genreId: "aaaaa",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "4444",
      name: "Piatto di Sushi di Lusso",
      genreId: "aaaaa",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "6666",
      name: "Burger Speciale",
      genreId: "bbbbb",
      price: 1000,
      image: "/buckwheat.jpg",
    },
    {
      id: "7777",
      name: "Ciotola di Riso ai Frutti di Mare",
      genreId: "bbbbb",
      price: 1300,
      image: "/buckwheat.jpg",
    },
    {
      id: "9999",
      name: "Pizza Classica",
      genreId: "bbbbb",
      price: 1100,
      image: "/buckwheat.jpg",
    },
    {
      id: "zzzz",
      name: "Patatine Fritte",
      genreId: "ccccc",
      price: 500,
      image: "/buckwheat.jpg",
    },
    {
      id: "xxxx",
      name: "Pollo Fritto Giapponese",
      genreId: "ccccc",
      price: 600,
      image: "/buckwheat.jpg",
    },
    {
      id: "wwww",
      name: "Insalata Fresca",
      genreId: "ccccc",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "tttt",
      name: "Menù per Bambini",
      genreId: "ddddd",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "ssss",
      name: "Menù Stile Giapponese",
      genreId: "ddddd",
      price: 1200,
      image: "/buckwheat.jpg",
    },
    {
      id: "rrrr",
      name: "Menù Cena Occidentale",
      genreId: "ddddd",
      price: 2000,
      image: "/buckwheat.jpg",
    },
    {
      id: "pppp",
      name: "Cola",
      genreId: "eeeee",
      price: 200,
      image: "/buckwheat.jpg",
    },
    {
      id: "oooo",
      name: "Succo d'Arancia",
      genreId: "eeeee",
      price: 250,
      image: "/buckwheat.jpg",
    },
    {
      id: "nnnn",
      name: "Tè Oolong",
      genreId: "eeeee",
      price: 220,
      image: "/buckwheat.jpg",
    },
    {
      id: "iiii",
      name: "Gelato al Matcha",
      genreId: "fffff",
      price: 400,
      image: "/buckwheat.jpg",
    },
    {
      id: "hhhh",
      name: "Piatto di Frutta",
      genreId: "fffff",
      price: 700,
      image: "/buckwheat.jpg",
    },
    {
      id: "gggg",
      name: "Budino",
      genreId: "fffff",
      price: 450,
      image: "/buckwheat.jpg",
    },
    {
      id: "ffff",
      name: "Biscotti Souvenir",
      genreId: "ggggg",
      price: 800,
      image: "/buckwheat.jpg",
    },
    {
      id: "cccc",
      name: "Chicchi di Caffè Speciali",
      genreId: "ggggg",
      price: 1500,
      image: "/buckwheat.jpg",
    },
    {
      id: "bbbb",
      name: "Tazza",
      genreId: "ggggg",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
};

export const sampleOrderItems = {
  ja: [
    {
      id: "1",
      name: "オムレツ",
      price: 900,
      image: "/omelet.jpg",
    },
    {
      id: "2",
      name: "天ぷら蕎麦定食",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  en: [
    {
      id: "1",
      name: "Omelet",
      price: 900,
      image: "/omelet.jpg",
    },
    {
      id: "2",
      name: "Tempura Soba Set",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  zh: [
    {
      id: "1",
      name: "煎蛋卷",
      price: 900,
      image: "/omelet.jpg",
    },
    {
      id: "2",
      name: "天妇罗荞麦套餐",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  ko: [
    {
      id: "1",
      name: "오믈렛",
      price: 900,
      image: "/omelet.jpg",
    },
    {
      id: "2",
      name: "덴푸라 소바 세트",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  es: [
    {
      id: "1",
      name: "Tortilla",
      price: 900,
      image: "/omelet.jpg",
    },
    {
      id: "2",
      name: "Set de Soba con Tempura",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  fr: [
    {
      id: "1",
      name: "Omelette",
      price: 900,
      image: "/omelet.jpg",
    },
    {
      id: "2",
      name: "Set de Soba Tempura",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  th: [
    {
      id: "1",
      name: "ไข่เจียว",
      price: 900,
      image: "/omelet.jpg",
    },
    {
      id: "2",
      name: "ชุดโซบะเทมปุระ",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  de: [
    {
      id: "1",
      name: "Omelett",
      price: 900,
      image: "/omelet.jpg",
    },
    {
      id: "2",
      name: "Tempura-Soba-Set",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  ru: [
    {
      id: "1",
      name: "Омлет",
      price: 900,
      image: "/omelet.jpg",
    },
    {
      id: "2",
      name: "Темпура Соба Набор",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
  it: [
    {
      id: "1",
      name: "Omelette",
      price: 900,
      image: "/omelet.jpg",
    },
    {
      id: "2",
      name: "Set di Soba Tempura",
      price: 1200,
      image: "/buckwheat.jpg",
    },
  ],
};
