package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"github.com/google/uuid"
)

// AccountAllergy represents a row from 'public.account_allergies'.
type AccountAllergy struct {
	ID         int       `json:"id"`          // id
	AccountID  uuid.UUID `json:"account_id"`  // account_id
	AllergenID int       `json:"allergen_id"` // allergen_id
}
