package db_model

// Code generated by xo. DO NOT EDIT.

// AllergenTranslation represents a row from 'public.allergen_translations'.
type AllergenTranslation struct {
	ID           int    `json:"id"`            // id
	AllergenID   int    `json:"allergen_id"`   // allergen_id
	LanguageCode string `json:"language_code"` // language_code
	Name         string `json:"name"`          // name
}
