package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"

	"github.com/google/uuid"
)

// CartItem represents a row from 'public.cart_items'.
type CartItem struct {
	ID               int          `json:"id"`                  // id
	CartID           int          `json:"cart_id"`             // cart_id
	MenuItemID       int          `json:"menu_item_id"`        // menu_item_id
	Quantity         int          `json:"quantity"`            // quantity
	AddedByAccountID uuid.UUID    `json:"added_by_account_id"` // added_by_account_id
	CreatedAt        sql.NullTime `json:"created_at"`          // created_at
	UpdatedAt        sql.NullTime `json:"updated_at"`          // updated_at
}
