package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Cart represents a row from 'public.carts'.
type Cart struct {
	ID             int          `json:"id"`               // id
	TableSessionID int          `json:"table_session_id"` // table_session_id
	TotalCartPrice int          `json:"total_cart_price"` // total_cart_price
	CreatedAt      sql.NullTime `json:"created_at"`       // created_at
	UpdatedAt      sql.NullTime `json:"updated_at"`       // updated_at
}
