package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Follow represents a row from 'public.follows'.
type Follow struct {
	FollowerID string       `json:"follower_id"` // follower_id
	FolloweeID string       `json:"followee_id"` // followee_id
	FollowedAt sql.NullTime `json:"followed_at"` // followed_at
}
