package db_model

// Code generated by xo. DO NOT EDIT.

// MenuCategoryTranslation represents a row from 'public.menu_category_translations'.
type MenuCategoryTranslation struct {
	ID             int    `json:"id"`               // id
	MenuCategoryID int    `json:"menu_category_id"` // menu_category_id
	LanguageCode   string `json:"language_code"`    // language_code
	Name           string `json:"name"`             // name
}
