package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// MenuCategory represents a row from 'public.menu_categories'.
type MenuCategory struct {
	ID           int          `json:"id"`            // id
	RestaurantID int          `json:"restaurant_id"` // restaurant_id
	CreatedAt    sql.NullTime `json:"created_at"`    // created_at
	UpdatedAt    sql.NullTime `json:"updated_at"`    // updated_at
}
