package db_model

// Code generated by xo. DO NOT EDIT.

// MenuItemAllergen represents a row from 'public.menu_item_allergens'.
type MenuItemAllergen struct {
	ID         int `json:"id"`           // id
	MenuItemID int `json:"menu_item_id"` // menu_item_id
	AllergenID int `json:"allergen_id"`  // allergen_id
}
