package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// MenuItem represents a row from 'public.menu_items'.
type MenuItem struct {
	ID           int           `json:"id"`            // id
	RestaurantID int           `json:"restaurant_id"` // restaurant_id
	CategoryID   sql.NullInt64 `json:"category_id"`   // category_id
	Price        float64       `json:"price"`         // price
	Available    sql.NullBool  `json:"available"`     // available
	CreatedAt    sql.NullTime  `json:"created_at"`    // created_at
	UpdatedAt    sql.NullTime  `json:"updated_at"`    // updated_at
}
