package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// MenuItemTranslation represents a row from 'public.menu_item_translations'.
type MenuItemTranslation struct {
	ID           int            `json:"id"`            // id
	MenuItemID   int            `json:"menu_item_id"`  // menu_item_id
	LanguageCode string         `json:"language_code"` // language_code
	Name         string         `json:"name"`          // name
	Description  sql.NullString `json:"description"`   // description
}
