package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Order represents a row from 'public.orders'.
type Order struct {
	ID           int             `json:"id"`             // id
	TableVisitID int             `json:"table_visit_id"` // table_visit_id
	Status       sql.NullString  `json:"status"`         // status
	TotalPrice   sql.NullFloat64 `json:"total_price"`    // total_price
	CreatedAt    sql.NullTime    `json:"created_at"`     // created_at
	UpdatedAt    sql.NullTime    `json:"updated_at"`     // updated_at
}
