package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// OrderItem represents a row from 'public.order_items'.
type OrderItem struct {
	ID         int          `json:"id"`           // id
	OrderID    int          `json:"order_id"`     // order_id
	MenuItemID int          `json:"menu_item_id"` // menu_item_id
	Quantity   int          `json:"quantity"`     // quantity
	Price      float64      `json:"price"`        // price
	CreatedAt  sql.NullTime `json:"created_at"`   // created_at
	UpdatedAt  sql.NullTime `json:"updated_at"`   // updated_at
}
