package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"

	"github.com/google/uuid"
)

// OrderedItem represents a row from 'public.ordered_items'.
type OrderedItem struct {
	ID            int          `json:"id"`              // id
	PlacedOrderID int          `json:"placed_order_id"` // placed_order_id
	MenuItemID    int          `json:"menu_item_id"`    // menu_item_id
	Quantity      int          `json:"quantity"`        // quantity
	Price         int          `json:"price"`           // price
	AddedByUser   uuid.UUID    `json:"added_by_user"`   // added_by_user
	CreatedAt     sql.NullTime `json:"created_at"`      // created_at
	UpdatedAt     sql.NullTime `json:"updated_at"`      // updated_at
}
