package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Payment represents a row from 'public.payments'.
type Payment struct {
	ID            int            `json:"id"`             // id
	OrderID       int            `json:"order_id"`       // order_id
	PaymentMethod sql.NullString `json:"payment_method"` // payment_method
	Amount        float64        `json:"amount"`         // amount
	PaymentStatus sql.NullString `json:"payment_status"` // payment_status
	CreatedAt     sql.NullTime   `json:"created_at"`     // created_at
	UpdatedAt     sql.NullTime   `json:"updated_at"`     // updated_at
}
