package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// PlacedOrder represents a row from 'public.placed_orders'.
type PlacedOrder struct {
	ID             int          `json:"id"`               // id
	TableSessionID int          `json:"table_session_id"` // table_session_id
	TotalPrice     int          `json:"total_price"`      // total_price
	CreatedAt      sql.NullTime `json:"created_at"`       // created_at
	UpdatedAt      sql.NullTime `json:"updated_at"`       // updated_at
}
