package db_model

// Code generated by xo. DO NOT EDIT.

// SchemaMigrationsSeed represents a row from 'public.schema_migrations_seed'.
type SchemaMigrationsSeed struct {
	Version int64 `json:"version"` // version
	Dirty   bool  `json:"dirty"`   // dirty
}
