package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Table represents a row from 'public.tables'.
type Table struct {
	ID           int          `json:"id"`            // id
	RestaurantID int          `json:"restaurant_id"` // restaurant_id
	TableNumber  string       `json:"table_number"`  // table_number
	Capacity     int          `json:"capacity"`      // capacity
	CreatedAt    sql.NullTime `json:"created_at"`    // created_at
	UpdatedAt    sql.NullTime `json:"updated_at"`    // updated_at
}
