package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// TableVisit represents a row from 'public.table_visits'.
type TableVisit struct {
	ID        int          `json:"id"`         // id
	TableID   int          `json:"table_id"`   // table_id
	StartTime sql.NullTime `json:"start_time"` // start_time
	EndTime   sql.NullTime `json:"end_time"`   // end_time
	CreatedAt sql.NullTime `json:"created_at"` // created_at
	UpdatedAt sql.NullTime `json:"updated_at"` // updated_at
}
