package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// TableGuest represents a row from 'public.table_guests'.
type TableGuest struct {
	ID           int          `json:"id"`             // id
	TableVisitID int          `json:"table_visit_id"` // table_visit_id
	GuestNumber  int          `json:"guest_number"`   // guest_number
	CreatedAt    sql.NullTime `json:"created_at"`     // created_at
	UpdatedAt    sql.NullTime `json:"updated_at"`     // updated_at
}
