name: migrate and generate model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/check-generate.yml'
      - 'backend/**'
      - 'graphql/**'
jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Postgres
        run: docker run --name postgres-test -e POSTGRES_DB=gaishi -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -p 5432:5432 -d postgres:16 &
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'backend/go.mod'
      - name: Install go tools
        run: make go-install-tools
      - name: Run migration
        run: make migrate-up
      - name: Run make gen
        run: make gen
      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected after running 'make gen'. Please run 'make gen' locally and commit the changes."
            git diff
            exit 1
          fi
