name: "Run Terragrunt Apply on main branch push"
on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/terragrunt-apply.yml'
concurrency:
  group: terragrunt-apply
  cancel-in-progress: true
jobs:
  run-terraform-apply:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: 'write'
      contents: 'read'
      id-token: 'write'
    steps:
      - name: setup repository
        uses: actions/checkout@v4

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.36.2

      - name: Login to Google Cloud
        id: auth
        uses: ./.github/actions/gcloud-auth.yaml

      - name: Terragrunt Init
        working-directory: infra
        run: terragrunt run-all init

      - id: terragrunt-fmt
        name: Check terragrunt fmt
        working-directory: infra
        run: terragrunt run-all fmt -check
        continue-on-error: true

      - name: Terragrunt validate
        working-directory: infra
        run: terragrunt run-all validate

      - name: Terragrunt plan
        working-directory: infra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod 755 $GITHUB_WORKSPACE/.github/scripts/tfwrapper.sh
          terragrunt run-all apply --terragrunt-non-interactive --terragrunt-tfpath $GITHUB_WORKSPACE/.github/scripts/tfwrapper.sh
